### ISSUE TITLE
On Manage Encounters screen, show Daily Budget

### ISSUE THREAD

**Issue by AlexMooney** [Asmor/5e-monsters#110] opened 2018-04-09 17:31 UTC
It would be great to be able to see how many encounters will fit into the daily budget.  Maybe to start, you could just add a "Total XP" and "Daily Budget" to the top of the manage encounters screen.  Showing the running total of XP on the encounter builder might be good too.

Eventually, you might want to be able to drag the encounters around to arrange them into different days.

**Comment by Asmor** [comment] 2018-04-09 18:03
Duplicate of #80

**Closed as completed by Asmor** 2018-04-09 18:03 UTC
Labels: duplicate
