### ISSUE TITLE
Link to information about the monster (e.g. on dndbeyond)

### ISSUE THREAD

**Issue by evyatron** [Asmor/5e-monsters#116] opened 2018-05-07 20:26 UTC
I would like to propose adding a link, both in the monsters table and the encounter info, to the monster on dnd beyond.

For example, a Bat would link to https://www.dndbeyond.com/monsters/bat .

I believe that could prove super helpful for people using mostly digital tools to run sessions.

**Comment by Asmor** [comment] 2018-05-07 20:28
Duplicate of #112

**Comment by evyatron** [comment] 2018-05-07 20:29
Ah was just editing to say I think it's different to that other one as I'm not talking about integrating an API into KFC, but rather a simple link-out to the page on dnd beyond, sorry!

**Closed as completed by Asmor** 2018-05-07 20:28 UTC
Labels: duplicate

**Comment by DeastinY** [comment] 2018-07-13 07:55
I'd be willing to look into the creation of the dndbeyond links.
Does anyone know, whether it would be legally safe to add a preview of the boxes on DDB to KFC? (See attached image). Thikingi about an [i] button on the monster that opens the panel and links to the full page.
![grafik](https://user-images.githubusercontent.com/5399476/42679593-cfe856c6-8682-11e8-9027-1d92294fcabd.png)
Furthermore I'm not sure, if all the monsters are available for free on DDB or you need to purchase the monster manual.

Anyways: awesome project! keep up the great work <3
